<?php

namespace App\Services\DB;
use App\Services\Collections\Collection;


class ActiveRecord extends EasyRecord
{
    protected function __construct($data)
    {
            foreach ($data as $key => $value)
            {
                if (in_array($key, static::$fields, true)) {
                    $this->$key = $value;
                }
            }
    }

    public static function find(int $id): null|array|self
    {
        $result = parent::find($id); // TODO: Change the autogenerated stub
        return new static($result);
    }

    public static function all($order = "DESC"): Collection
    {
        $result = parent::all($order); // TODO: Change the autogenerated stub
        foreach ($result as $key => $value)
        {
            $collection[] = new static($value);
        }
        return new Collection($collection);
    }
}