<?php

namespace App\Services\Queue;

use App\Services\DB\DataBase;
use JetBrains\PhpStorm\Internal\LanguageLevelTypeAware;

class Queue extends \SplQueue
{
	public function push(mixed $value): void
	{
		parent::push($value); // TODO: Change the autogenerated stub
		$pdo = new \PDO('mysql:host=db;dbname=php_8', 'root', 'o251298');
		$pdo->query("INSERT INTO autos (number, car) VALUES ($value, test)");
	}
}